### ISSUE TITLE
Accommodate CNV vcfs from GATK pipeline

### ISSUE THREAD

**Issue by sophie22** [eastgenomics/eggd_vep#13]
No normalisation is required (or can be done) on CNV vcfs, please make it optional. Both for when a panel is applied or not.
Example CNV vcf from GATK 4.2.5.0 on [DNAnexus](https://platform.dnanexus.com/projects/FzyfP204Z5qXBp6696jG5g10/data/output/dias_single_v1.3.0-CEN_v1.0.0-211217-1/GATKgCNV_call_v0.0.1_dev/CNV_vcfs?scope=recurse&name=segments)

**Comment by jethror1** [comment]
Closed by https://github.com/eastgenomics/eggd_vep/pull/17
